### ISSUE TITLE
Improve the discoverability of adding directory steps

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#101]
One usecase for CodeTour is when developers show others how to build or upgrade the technology. It would be helpful to visually create a tour step for a folder instead of a file. This helps when guiding users to upgrade materials.

**Comment by lostintangent** [comment]
We added support for ["directory steps"](https://github.com/vsls-contrib/codetour#directory-steps) a while back. Would this satisfy the user scenario here?

**Comment by gsmile** [comment]
Yes, however, this feature is not discoverable. Perhaps we can brainstorm about how to make this more discoverable, since I have heard feedback that customers want to do this in their training sessions.

**Comment by lostintangent** [comment]
Sounds great! I just wanted to confirm that this was about improving discoverability vs. there being something missing in the current implementation of "directory steps". I'll update the title of this issue in order to reflect this detail 👍

**Comment by gsmile** [comment]
Thanks! I've also heard some feedback that this feature points the tour step to a default file. I haven't been able to reproduce it but the customer insists that it's been happening to them.

**Comment by gsmile** [comment]
Hi @lostintangent there is a bug here - if the directory step is the first step in the tour, then CodeTour doesn't open the step. Directory steps only seem to work when they are not the first step in the tour.

**Comment by lostintangent** [comment]
This bug has been fixed in `v0.0.45`. Let me know if you have any further feedback!
