### ISSUE TITLE
Add lines in code with ability to fastforward

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#103]
One way to use CodeTour is to guide developers to insert code where necessary. One team would like the ability to insert lines of code in specific spots with the ability to fast-forward or rewind the process without breaking the codebase.
Scenario:
1. Developer is on Step 1 of CodeTour that contains instructions to "insert code" (with 1 click)
2. Developer "fast-forwards" to step 5 where the code was already inserted, and the codebase does not break

This suggestion comes from the PnP team.

**Comment by lostintangent** [comment]
By "fast forward", do you mean that the end-user can specify that they want to skip ahead steps, but have the intermediate steps "process" their associated code injections? I'm not really sure how we would allow this intuitively in the UI, without overcomplicating the experience for other use cases.

@gsmile Did you have thoughts on the priority or design for this?

**Comment by gsmile** [comment]
Yes, your interpretation is correct for this. The scenario for this would be when a user is attempting to upgrade using software, which means things would break without a critical line of code. 

Perhaps a potential design could be having an "Update Code" button, where all the code that was missing prior to this step is added. 

Customers tell me that this would be extremely useful for teaching and upgrade scenarios, but I have not heard that this feature is blocking.

**Comment by lostintangent** [comment]
I'm going to close this for now, since it's fairly specific to the upgrade scenario, which isn't really a priority for CodeTour. If folks want us to prioritize this use case/capability, then please feel free to re-open this. Thanks!
