### ISSUE TITLE
Associate tour with git commit to track thought process

### ISSUE THREAD

**Issue by chrisokuda** [microsoft/codetour#107]
**What I am looking for:**

I would like to be able to "record" a coding session with context for my decision making. The recording would be best in a text-only format (video is too large for long projects, sorry [Chronicler](https://marketplace.visualstudio.com/items?itemName=arcsine.chronicler)), and it wouldn't have to follow keypresses, only individual commit level granularity. I would like to be able to record some comments with code context and also add additional steps and other features, **_pretty much exactly like CodeTour_**, but with the ability to edit code at the same time and record my progression.

**How it might work:**

I wonder if you could just track the currently checked out commit along with each recorded step in the CodeTour data structure, then when playing it back later checkout that commit at the same time? I am not sure if you would need to track branches or anything else (or if you would have to save/not delete merged branches), but if you could track the git repo status across each git operation, and additionally to that feature, pause and resume a recording session, then I could record the start of a project, comment on commits as I make them (with context!) and pause it at the end of the day. I could resume it the next day, and continue. I could do this all the way through a project, and have a set of files from CodeTour that give me context for my decisions that aren't just git commit messages with no context.

**Thanks!**

Would this be a feature anyone else could use, or that you could implement easily? I am not a git-whiz or a vscode-extension-whiz, so I don't want to assume this would be as easy as I imagine above, so feel free to shoot this down if it's not within your own vision or is impossible :+1: 

Also, thank you for reading/considering this request!

**Comment by gsmile** [comment]
Hi @chrisokuda, thank you for submitting this request! To clarify, are you looking for an easier or faster way to start and stop recording while you are writing code, and attaching it to a specific commit or pull request? We have heard that developers are creating CodeTours to record their thought process while they write code, and we have gotten requests for attaching CodeTours to Github pull requests as well.

**Comment by chrisokuda** [comment]
Hi @gsmile thanks for responding!

The commit, not PR (I don't really use GitHub).

I would enjoy it if I could easily start and stop recording and have each comment (or whatever other item) associated with the git repo status automatically, so perhaps just the commit hash? (I don't know if a hash is sufficient to track the whole git repo "state", but probably necessary.)

I can't find anything similar that would do what I am describing: a sort of "screen recording, with contextual comments" on a git-commit granularity, and CodeTour seems to have most of the features I need other than automatic association to the git repo "state" at that point in time (or maybe it does? that would be embarrassing if I overlooked it!).

**Comment by gsmile** [comment]
This is an interesting suggestion! We don't have this functionality yet, especially with that level of granularity, but we can look into this. It could be very useful for a lot of developers. Thank you for this.

I'd be curious to know, what kind of git tools do you use? Who do you foresee would mostly view the recorded CodeTours that are attached to a commit?

**Comment by chrisokuda** [comment]
@gsmile Thanks for the consideration!

This would be a tool mostly for the developer of a repo, so they can remember their decisions as they make them and why, with context, like a dev log but with a lot more context.

So for example, if I have some file and I write a new complex function, then I could commit it progressively (several commit "steps") and record several steps in CodeTour explaining how it worked and why I made certain important or meaningful decisions. I could then, as I test the function later and bugfix it, add steps to the tour which would explain why I switched from one algorithm to another:maybe it was faster? less buggy? I can even show examples of the tests and command-line runs with CodeTour!

I can't do this easily with just a dev log. (You could call this a "dev log" mode, perhaps.)

I do see now I can associate tours to different refs (branches, etc.), so I'll try CodeTour to see if I can make a sort of "multi-tour" workflow of what I am describing here (one tour each branch maybe?) This would require a whole bunch of separate tours, but maybe I can just keep each branche's tour in it's own branch and not in master, then save all my branches? Either way it seems like I will have either a lot of tours listed in CodeTour or a lot of old, stale branches in git. I also considered a single branch with tags for this workflow, but then I have to continually switch branches as I make single commits, add the commit to the tour branch somehow (yuck, merges and cherry-picking), then add steps, then commit the steps, then switch back to the working branch, etc. which does not work for a "dev log" mode.

I think one "master tour" that cuts across branches and commits automatically would be more efficient than other workflows I can think of for what I am describing, so I still think this feature would be great!

**Comment by gsmile** [comment]
Love this idea! We have heard from other developers who want to do something similar, and we've done a lot of research showing that something like this would be helpful. Thank you so much for your detailed feedback! 

One way you could achieve something close to a "temporary brain cache" like you're describing is creating separate refs like you're saying, and removing them as necessary. Perhaps as a rough first step, would an option to nest and collapse tours in the list of tours help you achieve this, if you were to create separate tours for each commit?

**Comment by chrisokuda** [comment]
I think a way to have a sub-tour nested within another tour would be a great feature which would help initially, yes!

For now, I plan on using the "command" feature (`>>>` I think), where you can type a command and click it to run in the terminal, to add a `>>> git checkout <hash>` link for whatever commit I am discussing, so it might not be automatic, but at least I have a ref listed that I can checkout manually just by clicking to open a terminal.

Thanks again for the consideration and the work on this extension!

**Comment by gsmile** [comment]
Great, thanks so much for your feedback! These are great suggestions. We will look into prioritizing them.

Thank you for your support! cc @lostintangent is the dev behind this extension!

**Comment by itggot-linus-styren** [comment]
I would love to use this feature for teaching purposes. I have been experimenting with stepping through code one commit at a time with small incremental code changes using git checkout command. I wrote a hacky script to accomplish this [here](https://gist.github.com/itggot-linus-styren/f84a27255b43b07ca9f4a8bbcc7debe5) which allows me to run `gn` command from the terminal to go to the next commit. I have also given this to my students which allows them to step through the material that we cover after the lessons and can modify the code at any point.

This method of teaching has been very effective and allows the students to easily follow the material without having to focus on copying the source code that the teacher is writing. Much better than code-alongs IMO.

What is the status of this feature? I would be happy to contribute to this feature.

**Comment by lostintangent** [comment]
Now that yours can be [linked into a sequence](https://github.com/microsoft/codetour#linking-tours), and a tour can already be associated with a commit, I believe this capability is now unblocked, by means of creating a series of tours. One for each commit. 

I'm going to close this as resolved, but please let me know if there are still gaps in the experience that you'd need. Thanks!
