### ISSUE TITLE
Multiple Choice Questions

### ISSUE THREAD

**Issue by gracegtaylor** [microsoft/codetour#109]
While we're seeing CodeTour used as a learning tool more and more often, instructors are looking to assess student progress to recommend next steps and lessons. 
Instructors are looking to implement multiple choice questions into a CodeTour step and get exported student data to guide formative assessment.

**Comment by lostintangent** [comment]
In general, we haven't seen significant interest in CodeTour for tutorials, and therefore, I'm going to close this issue for now. Please re-open it if you'd like to discuss prioritizing this enhancement. Thanks!
