### ISSUE TITLE
Option for larger font size when playing tour

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#111]
When devs are presenting code or scrolling through new codebases, the tour itself may blend into the code and devs have a hard time finding their place again. Customers have requested to be able to customize font size or font for CodeTours.
Stage 1: Option for larger font size when playing tour
Stage 2: Option for author specify specific font size or family when recording tour

**Comment by lostintangent** [comment]
Currently, the only way to increase the tour step font size, is for the end-user to zoom VS Code in general (e.g. by pressing cmd+). Since the tour steps are defined as markdown and rendered by VS Code, we don’t have control over styling, outside of the things that are allowed by markdown itself (e.g. headings, links, lists, etc.). So if zooming in wasn’t sufficient, then we’d need to think about how else to  address this.

**Comment by lostintangent** [comment]
@gsmile What’s your thoughts on the next steps? I’m not aware of any good options here based on current VS Code support. And so we may need to spec out what we want the experience to be and then see if we need to make any asks on the VS Code team.

**Comment by gsmile** [comment]
Great question! I believe that to enable a better presentation experience, if we could adjust font size of the steps independently of the rest of the screen through the click of an icon (like a magnifying glass) that would be great!

Currently, here's an example of what zooming in would look like if I'm presenting code:

![Zoom_Issue](https://user-images.githubusercontent.com/12738587/102155556-c561fc80-3e49-11eb-9237-0fefb34f455f.jpg)

**Comment by lostintangent** [comment]
From a prioritization perspective, I could imagine that we consider presentation scenarios as P2 (for now), while we focus on training/tutorials/general-purpose code onboarding scenarios. What do you think? If so, we could make an ask on VS Code to allow more UI customization support, and then revisit this as part of a broader focus on improving presentations in the near future.

**Comment by gsmile** [comment]
That sounds like a good plan! I'll change the prioritization. :)

**Comment by lostintangent** [comment]
Closing this as resolved!

**Comment by dagilleland** [comment]
@lostintangent Is this really resolved? There's a link from this issue to #104, which closes out with a link back to this issue - #111.

Yes, it looks like the only resolution to this issue is that it's a P2 label instead of P1. But what does that mean?
