### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by lostintangent** [microsoft/codetour#12]
Currently, the tour is entirely text-driven. However, it could be really interesting to explore how to allow recording audio as well, and associating that with specific steps in the tour.

**Comment by remisharrock** [comment]
I add also the possibility to record the position of the mouse cursor (relative the code) synchronized with the audio; that would be awesome !

**Comment by lostintangent** [comment]
Closing this due to lack of interest, and the fact that there are probably better tools that can handle audio/video.

**Comment by vaddisrinivas** [comment]
This could be a really interesting feature, that can make illustrations very helpful. Please LMK if there was any further work on this!
