### ISSUE TITLE
Disable automatic info balloons during start-up

### ISSUE THREAD

**Issue by gsmachado** [microsoft/codetour#122]
First of all: awesome extension! Great work! 👍  💯  💪 

Is there some kind of config (e.g., through the `settings.json` or something) that people can disable balloons like this one?

![image](https://user-images.githubusercontent.com/2124276/105099722-6b89cd80-5aac-11eb-9d9d-08f5c52b5c93.png)

I'm creating a dockerized vscode instance with codetour and it would be great to disable that.

thanks! 🙏

**Comment by lostintangent** [comment]
There isn't currently a setting to suppress this, but we could definitely add that. Maybe something like `CodeTour > Prompt for Workspace Tours`? And it could be disabled in the `settings.json` file for a repo?

@gsmile Thoughts?

**Comment by gsmachado** [comment]
@lostintangent 

Agreed.

Something like `CodeTour > Prompt for Workspace Tours` for typical users (activating/deactivating this in the VSCode UI) is fine, yes.

But it's also important to have an option in the `settings.json`, like

```
"codetour.promptForWorkspaceTours": false
```

since that, for some use cases, is important to ship the `settings.json` already with the correct options. 👍

**Comment by gsmile** [comment]
@gsmachado Thank you for the suggestion. Out of curiosity, are you wanting to suppress this because it becomes annoying for people who know the codebase, or because not many people who use the codebase are new?

**Comment by gsmachado** [comment]
> @gsmachado Thank you for the suggestion. Out of curiosity, are you wanting to suppress this because it becomes annoying for people who know the codebase, or because not many people who use the codebase are new?

It's more about having an extension using CodeTour to extend its functionalities.

I will briefly explain my use case.

I'm developing an extension that provides a brief introduction of "code templates" in a "Welcome" markdown file. In this markdown, there's a button (using the Command URIs) where the `codetour.startTour?[params]` command is invoked -- specifically to the code tour of a template.

Then, imagine that once the user (developer) starts VScode, with a specific code template (i.e., git repo, with some examples), the user will see the "Welcome" markdown file with instructions (including a button to start the tour) **AND**, at the same time, a balloon from the CodeTour extension also advising to start the tour. This is redundant and confusing, in my humble opinion.

Adding an option to suppress this `Prompt for Workspace Tour` balloon (and possibly other options) would turn CodeTour way more interoperable with other extensions that depend on it.

I'm focusing here on a single option, but maybe there are other options that could be customized to a workspace. CodeTour is simply great, but maybe extensibility is also an important factor moving forward. 😄 

That's my 2 cents.

**Comment by gsmile** [comment]
@gsmachado Thanks for the feedback. That makes a lot of sense and I agree that it's confusing to have two toasts for the same activity. 

I have a few additional questions to help us understand how you use CodeTour: 
- What language are the code templates written in? 
- Do the CodeTours typically become outdated once someone uses the template to write their own code? Does this matter to you?
- Do you expect people who use CodeTours to update the template file to include their own code, or do you expect them to use the template file for reference to write their own separate code?

@lostintangent I think giving tour authors the option to suppress the toast will be a good idea for extensibility functionality.

**Comment by lostintangent** [comment]
@gsmile Yep agreed! I like the suggestion of adding a VS Code setting to suppress this toast, and then that setting could either be defined by the end-user, or included in a repo. I'll go ahead and add that setting this week 👍

**Comment by gsmachado** [comment]
> * What language are the code templates written in?

Our project is still working in progress, but it will support code templates used by many languages. Primarily, the ones supported are Java, C#, Golang, Typescript, and Python. We should add others later on.

@gsmile @lostintangent If you're interested, follow me on Twitter. Once I announce our project you will see it, try it out, and we can even DM each other to exchange some ideas. I'm working with Developer Experience in a blockchain project, and I'm keen to provide better tools based on VSCode.

I don't post much, but check it out: https://twitter.com/gsmachado

> * Do the CodeTours typically become outdated once someone uses the template to write their own code? Does this matter to you?

Yes, usually it gets "outdated" since the new code written by the user "messes" a bit with the code tour.

> * Do you expect people who use CodeTours to update the template file to include their own code, or do you expect them to use the template file for reference to write their own separate code?
> 

Both. 

Once the user chooses a code template to try it out, the VS Code environment is built and the user is redirected to it. Then one of our extensions detects which code template was chosen and it displays the "Welcome" page. On the welcome page, the user can click on the button "Start CodeTour" to effectively start, e.g., the 'Intro' Code Tour. It can vary from code template to code template, and that's why I prefer to develop a custom "Welcome" page to trigger a specific Code Tour.

Then the user can follow the code tour, go back and forth, and probably new code will be added/removed. OR, another possibility is: he will download key files from the code template and start his project from scratch (in his local machine).

So, I see value in both ways of doing things.

**Comment by lostintangent** [comment]
This has now been resolved! The latest extension version includes a `codetour.promptForWorkspaceTours` setting that you can set to `false` in order to suppress this dialog 👍

**Comment by gsmachado** [comment]
@lostintangent cool! thanks a lot!

**Comment by lostintangent** [comment]
Let us know if you have any other feedback/issues. Also, if you end up using CodeTour in your product, we'd love to share in the excitement with you 😄
