### ISSUE TITLE
Directory tour step doesn't load

### ISSUE THREAD

**Issue by adierkens** [microsoft/codetour#128]
When trying to record or play a tour, nothing happens when you hit a `directory` step. 
I attached a video of me trying to record a tour that includes a `directory` step as well as playing it back. I would expect to see an means of editing the `description` of the step as well as something displayed when that step is reached in the play-back. 

https://user-images.githubusercontent.com/13004162/107425476-ddfe3400-6ad3-11eb-9caf-9243281663fd.mov

VSCode Version: 1.53.0
Codetour Version: 0.0.43

**Comment by lostintangent** [comment]
Ah interesting. Looks like we regressed directory steps. I'm taking a look right now!

**Comment by gsmile** [comment]
@adierkens Thanks for creating this issue, Adam. Out of curiosity, how were you planning to use CodeTour? We are trying to optimize the product for some common usecases, especially for developers who want to maintain tours.

**Comment by adierkens** [comment]
There's 2 different use-cases that I was looking into

The first was around first-time contributors to one of the frameworks I work on. I was thinking it would include a few different tours that scaled from intro/getting started (basic install, build, test), then a project overview/structure, basic data-flow, and maybe a few more detailed walk-throughs of some of the more complicated sub-systems.

The second use-case I was looking into was one around how to onboard to the project. Maybe start with an empty repo (or basic create-react-app) and use a codetour as a self-guided tutorial to onboard to the framework.

**Comment by lostintangent** [comment]
This has now been resolved in the latest extension release: v0.0.44. It's being published to the marketplace right now and should be available for update in the next few minutes. Thanks again for reporting this issue, and please let us know if you run into any other problems 👍
