### ISSUE TITLE
Drag and drop to rearrange steps

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#133]
The ability to drag and drop steps in the tour tree would greatly improve usability for creating and maintaining tours. Customers expect to be able to drag and drop steps to rearrange order of steps within a tour, and drag and drop to move a step from one tour to another.

**Comment by lostintangent** [comment]
This isn't possible with the current VS Code APIs, and so I wonder if we should drop the priority a bit? I also just tagged this to indicate the need to get VS Code support.

**Comment by lostintangent** [comment]
I'm going to close this for now, since it doesn't seem like there will be a VS Code API for this anytime soon. The best solution is likely to be a custom webview tree, but that would be a decent amount of work. So we can wait to hear more feedback before prioritizing this work.
