### ISSUE TITLE
Fix screen reader functionality

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#136]
Some developers who use a screen reader have commented that CodeTour/VS Code doesn't allow use of the virtual PC cursor, which limits functionality for people who use a screen reader. The virtual PC cursor allows the developer to navigate the tools just like any other webpage. Currently, developers who use a screen reader are limited to using CodeTour by cycling through the tabbed items.

Further investigation is needed for how to understand how CodeTour/VS Code could work for people who use screen readers.

**Comment by lostintangent** [comment]
VS Code are addressing accessibility support across the editor 👍
