### ISSUE TITLE
"Back" button when viewing linked tour step

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#137]
Some tour authors implement links to multiple steps within a tour step. When navigating through tours and exploring step references, it is useful to be able to click a "back" button in order to go back to the original referencing step.

User Experience
- I click a link inside a step (A) that references another step (B)
- I see step (B) open in the codebase beside the respective line of code
- I see a "back" button in step (B) which I can press to bring me back to step (A)

**Comment by lostintangent** [comment]
Great suggestion! Would we only show the `Back` button immediately after the step navigation? For example, if I jumped from A->C, and then clicked the `Next Step` link, would I still see the `Back` button to jump to `A`? Or would that "go away" as soon as I move from C to another step?

Even beyond a back button, we could discuss have "back references" in general, where we display the list of steps that reference the current step?

**Comment by gsmile** [comment]
If a user goes through the flow for A->C->D, clicking back would take them to C, and clicking back another time would take them to A. I think this mirrors the browser "back" button behavior where you can keep clicking back to revisit pages you've visited before. How does that sound to you?

Regarding "back references," that could be a help feature to implement if developers are creating tours that reference a lot of different steps, especially if they have steps that jump around.

**Comment by lostintangent** [comment]
Resolved!
