### ISSUE TITLE
Request: Option to Keep Code Tour Panel closed

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codetour#148]
## Scenario

While demo-ing live or in videos, I use the keyboard to progress through the code tour. I only want the Explorer panel to be open and keep the distractions hidden. I generally collapse the Code Tour panel. However, while going through the Code Tour the panel auto expands and highlights the step. This may be desirable in some situations (seeing where you are as a self-paced-learner). However, it distracts the learners' eyes away from where I want them to look when I am telling the demo
s story in a video or live.

## Request

While progressing through a Code Tour, I'd like the option to keep the panel closed.

Could a setting be created to allow the code tour to stay collapsed? Something like `showCodeTourAsYouProgress` (terrible name :) )

**Comment by lostintangent** [comment]
Hey! Yeah this is a great suggestion. I currently check to see if the `CodeTour` tree is visible, but that visibility only tracks if the `Explorer` tab is focused. And so I'm not sure if I'm (currently) able to prevent focusing the view if you have it collapsed. I'll add this setting for now, and in parallel, I'll file a request on VS Code to provide an API for me to respect the collapsed state, without needing to rely on a setting.

**Comment by lostintangent** [comment]
This should now be fixed. If you collapse the `CodeTour` tree and navigate a tour, it shouldn't auto-expand the tree. Let me know if you run into any issues with that. Thanks again for the feedback!
