### ISSUE TITLE
Request: Add Start and End Tour keyboard shortcuts

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codetour#149]
While walking through a tour we can keep our hands on keyboard most of the time. But ending the tour taking either going to the command palette and typing end tour (my pref today) or using the mouse/trackpad. It would be nice to end the tour with a keystroke. 

The next and previous keystrokes are CMD+LeftArrow and CMD+RightArrow. It would be nice to keep it in the same area. Perhaps the following (see image below).

Notice that I also added a Start Tour keystroke, with a less restrictive WHEN expression.

I chose double tap on the up and down arrows because the Start Tour would otherwise conflict with an important key combo.

This may just be a personal preference ... but I thought I'd suggest it just in case. 

**I'd be happy to make this PR if you are open to it.**

![image](https://user-images.githubusercontent.com/1202528/110958620-e1771c00-831a-11eb-9c03-1621c4402b59.png)

**Comment by lostintangent** [comment]
Hey! This is a really great suggestion, and I'd love to have the PR 🙌

**Comment by lostintangent** [comment]
This has been added in `v0.0.47` 👍🏻

**Comment by Ang-YC** [comment]
Hi, this default keybinding is conflicting with keybinding for `cursorTop` and `cursorBottom`, which is commonly used to jump to the beginning / end of file.

In my opinion VSCode default is more important, please consider changing this keybinding to something not so common.

Thanks

**Comment by lostintangent** [comment]
Hmm, I didn't realize that! I definitely don't want to interfere with existing keybindings, and so let me take a look at this.

BTW, I'm assuming that the issue here is with the "start tour" keybinding, and not the "end tour" keybinding? The later is only activated when you're within a tour, and so shouldn't be too disruptive?

**Comment by Ang-YC** [comment]
Hi @lostintangent, thanks for your fast response!

Yes the issue here is with the "start tour" keybinding, "end tour" seems to be okay :)
