### ISSUE TITLE
Support inserting multiline code blocks.

### ISSUE THREAD

**Issue by plisy** [microsoft/codetour#155]
Right now, single line code blocks get `Insert Code` link: 

    ``` sh
    echo "Hello, World!"
    ```

![image](https://user-images.githubusercontent.com/1951942/113058503-0fee5700-9163-11eb-9efb-52956a593f46.png)

But multiline code blocks don't

    ``` js
    function Helloer() {
        console.log("Hello, World!")
    }
    ```
![image](https://user-images.githubusercontent.com/1951942/113058648-462bd680-9163-11eb-902f-b9cfbd5032fd.png)

**Comment by emtei** [comment]
@plisy You have posted the same picture twice. 
Issue is easy to reproduce `Insert Code` is missing under second code snippet:
![image](https://user-images.githubusercontent.com/6403957/114467380-23c99c80-9bea-11eb-927e-db5a84fd3d77.png)

**Comment by arothian** [comment]
Is it possible to get a release with this fix?

**Comment by lostintangent** [comment]
Yep I'm preparing a release with this fix right now. Stay tuned!
