### ISSUE TITLE
Please match fontsize in the tour panel UI to editor.fontSize?

### ISSUE THREAD

**Issue by palaniraja** [microsoft/codetour#159]
The font size in code tour panel should match the editor size or have a custom fontsize settings to use this large monitor/projectors

<img width="1752" alt="codetour-suggestion" src="https://user-images.githubusercontent.com/124864/114289426-9e4cbd80-9a2c-11eb-8a74-954c51298ebd.png">

**Comment by lostintangent** [comment]
CodeTour doesn't currently set the font-size, and I'm actually not sure if it's controllable.

@rebornix Is this a bug in VS Code? I'd imagine that the comment font size would want to match the editor font size?

**Comment by lostintangent** [comment]
This should now be resolved 👍

**Comment by lostintangent** [comment]
Yeah this is unfortunately a bug on VS Code itself, and isn't something that CodeTour is able to control :/
