### ISSUE TITLE
"Insert Code" link dissapears while editing step

### ISSUE THREAD

**Issue by arothian** [microsoft/codetour#161]
Editing a tour step that contains a code block with a `Insert Code` link using the `Change Line` option in the UI causes the `Insert Code` to be removed from the step preview. 

Editing the step markdown contents again makes the link re-appear.

**Comment by arothian** [comment]
Looks like it also happens if you edit the step markdown without changing anything and hitting save. The link disappears.

**Comment by lostintangent** [comment]
Interesting! Let me take a look and see what might be happening here. If you navigate to and from the step, I assume the link comes back? And therefore, it just disappears temporarily after the gestures you mentioned?

**Comment by arothian** [comment]
Yeah, it comes back if you navigate back to the step by another means, so it's only temporary UI glitch it seems.

**Comment by arothian** [comment]
Looks like there is a similar UI issue with the styling for the `>>` syntax for executing a command. It duplicates the ">>" formatting in the step window when you edit it. It goes back to the single ">>" when you leave the step and return.

Minor thing though.

**Comment by lostintangent** [comment]
This appears to be a bug in the comment API in VS Code. Let me file a bug on them and see if we can get it resolved 👍

**Comment by lostintangent** [comment]
Hmm, I'm not able to repro this. Just to confirm the repro steps:

1. Navigate to a tour step that includes a code snippet or shell command
2. Click the `...` menu and select `Change Line`
3. Edit the line number and accept

Is that accurate? After I do these steps, the shell commands and `Inject code` link continue to show up for me?

**Comment by lostintangent** [comment]
I'm going to close this for now, since it seems like it _might_ have been resolved. Please re-open if that isn't the case though. Thanks!
