### ISSUE TITLE
Use `primitive-square` instead of `debug-stop`

### ISSUE THREAD

**Issue by misolori** [microsoft/codetour#165]
Suggestion to use the "square" icon instead of the debug stop button (which is thicker and red):

## Current
![image](https://user-images.githubusercontent.com/35271042/116107889-43d87180-a668-11eb-907b-8f6541be4bc1.png)

## Suggestion
![image](https://user-images.githubusercontent.com/35271042/116108190-88640d00-a668-11eb-909d-519036e137c7.png)

**Comment by lostintangent** [comment]
Ah great suggestion! Changing that now 👍🏼

**Comment by lostintangent** [comment]
Fixed! While I was at it, I replaced `debug-start` with `play` as well. Let me know if that's the wrong thing 😄

**Comment by lostintangent** [comment]
I'm publishing an update to the marketplace right now 👍🏼
