### ISSUE TITLE
API Usage Example

### ISSUE THREAD

**Issue by NotMyself** [microsoft/codetour#168]
Is there an example of how to use the extension API described [here](https://github.com/microsoft/codetour#extension-api)?

I want to start a specific tour from my learning extension. The relevant code:

```typescript
configureLab = async (): Promise<void> => {
    const workspace = this.getLabWorkspace();
    const labEnv = await this.getLabEnvironment();

    //deploy lab tenant resources
    if (workspace !== undefined && labEnv !== undefined) {
      if (labEnv.resources) {
        const uri = getFileUri(
          `/.auth0/lab/${labEnv.resources}`,
          workspace.uri
        );
        await executeCommand('auth0.deploy', uri);
      }

      //write local environments
      if (labEnv.clients || labEnv.resourceServers) {
        await executeCommand('auth0.lab.localConfigure', labEnv);
      }

      //issue post command to kick off next process
      if (labEnv.postConfigureCommand) {
        executeCommand(labEnv.postConfigureCommand);
      }
    }
  };
```
The very last step is to fire the post command if it exists. I want to be able to start a tour here but I am not sure how to access the API.

**Comment by lostintangent** [comment]
Do you want to be able to programmatically start a specific tour by title? You can see an example calling the CodeTour API [here](https://github.com/lostintangent/codeswing/blob/59635fab5a8ce684724ab420451b3ef2444d8d47/src/preview/tour.ts#L53), but it's not as simple as it could be. With the current API, you'd need to read the your file, parse it into JSON, and then call the "startTour" API, passing the tour object and the URI of the workspace.

That said, I can probably simplify this quite a bit, if you let me know how you'd like to discover/specify the tour to start 👍

**Comment by NotMyself** [comment]
Yeah basically, I want to handle when the tour is started and monitor progress from my extension. This will give me the opportunity to make xAPI calls or resume based on progress.

**Comment by lostintangent** [comment]
Ah OK interesting. Would you primarily be interested in being notified when a tour is started and progressed? We have APIs for that as well?

**Comment by NotMyself** [comment]
That would be great! I would also like to be able to start a specific tour by path.

**Comment by NotMyself** [comment]
After some digging, I found a way to kick off my tours. Here is the utility file I created for integration.

```typescript
import * as vscode from 'vscode';

async function getExtension(): Promise<vscode.Extension<any>> {
  const ext = vscode.extensions.getExtension('vsls-contrib.codetour');
  if (ext && !ext?.isActive) {
    await ext?.activate();
  }

  if (!ext) {
    throw new Error('Cannot load CodeTour extension');
  }

  return ext;
}

export async function startTour(uri: vscode.Uri) {
  const ext = await getExtension();
  const api = ext.exports;
  api.startTourByUri(uri);
}

```
