### ISSUE TITLE
Codetour support for GitHub Codespaces running in Safari?

### ISSUE THREAD

**Issue by bomberstudios** [microsoft/codetour#177]
I was trying to use Codetour on one of my Codespaces, and apparently it does not work _at all_ on Safari (Version 14.1.1 (16611.2.7.1.4) running on macOS 11.4).

Opening the Codespace on Chromium it works as expected. I’m not sure if this is a Codetour thing, or a Codespaces thing (or, alas, a Safari thing) so apologies if this is not the right place to file this.

Thanks in advance for your time, and thanks for creating this awesome extension!

**Comment by lostintangent** [comment]
Thanks for reporting this! I actually work on Codespaces (CodeTour is a side-project), so I'd obviously love to make sure this is working properly. Let me take a look at this today and see what's going on. Stay tuned!

**Comment by bomberstudios** [comment]
Thanks!

**Comment by lostintangent** [comment]
I was able to verify that CodeTour works great in Safari, but I'm not using Big Sur. So I'm going to update that today and see what might have regressed.

**Comment by lostintangent** [comment]
This issue has been fixed!

**Comment by bomberstudios** [comment]
Thank you so much! 🙌🏼
