### ISSUE TITLE
Unable to install on Code OSS and VS Codium

### ISSUE THREAD

**Issue by palnabarun** [microsoft/codetour#178]
Codetour is showing the following error on Code - OSS and VS Codium:

OS: Manjaro with Kernel 5.11.18

### Code - OSS
```
Unable to install 'vsls-contrib.codetour' extension because it is not
compatible with the current version of VS Code (version 1.56.2).
```

Installed from https://archlinux.org/packages/community/x86_64/code/

### VS Codium
```
Unable to install 'vsls-contrib.codetour' extension because it is not
compatible with the current version of VS Code (version 1.57.0).
```

Installed from https://aur.archlinux.org/packages/vscodium-bin/

I tried the same on VSCode 1.57.0 and it installed successfully. VS Codium and VS Code in this case are both built from the same commit (https://github.com/microsoft/vscode/commit/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c) and show the same message on `Help > About`.

Does it mean that Codetour is not supported on Code - OSS and VS Codium builds?

I can probably understand that Code - OSS being a minor version older (v1.56.2) may not be supported by the extension, but it is pretty weird that VS Codium is not supported even though commits from which it is built is the same as VS Code.

PS: The demo of the extension looked really cool! Great work on this! 💯 

Edit: Added sources of installation and OS.

**Comment by lostintangent** [comment]
CodeTour is currently marked as requiring [v1.48+](https://github.com/microsoft/codetour/blob/main/package.json#L21), so I'm not sure why you'd be getting this error. Do you see other extensions having issues supporting these alternative builds of VS Code? I don't have any experience using them, so I'm not really sure if there are interop challenges here.

**Comment by lostintangent** [comment]
Closing this for now since I'm not aware of any issues/changes needed in CodeTour to support this. If you're still encountering this issue, please re-open it and I can try to investigate. Thanks!
