### ISSUE TITLE
Reference workspace-local images from step

### ISSUE THREAD

**Issue by lostintangent** [microsoft/codetour#18]
Currently, you can author your step descriptions using markdown, which includes support for referencing HTTP-based images. However, you can't currently reference images that are local to the codebase, which is a little limiting. It would be awesome if you could add something like the following to a step comment and it would work (assuming that the path was valid in the current workspace): `![image](./images/foo.png)`. That way the repo could include the codebase, the tours and any associated images.

**Comment by lostintangent** [comment]
This isn't possible today, due to a limitation in the VS Code comments API. We'll file an issue on the VS Code repo to track this request.

// CC @rebornix

**Comment by lostintangent** [comment]
This has been resolved 👍🏼

**Comment by dgilleland** [comment]
@lostintangent - You state it's been "resolved", but I don't see the link(s) to where it is actually implemented. I get in a "loop" between issues #18, #106, and microsoft/vscode#93028 (the last of which is still open).

So, for those reading this, it's still an open issue in backlog (as of Sep 7, 2021).

**Comment by lostintangent** [comment]
I actually worked around the VS Code issue by "rewriting" the image URL. And so the VS Code issue is still open, because VS Code hasn't added native support for referencing images from a comment. However, CodeTour added support to it on its own. 

Are you not seeing it when, when you add a relative file path? Note that the path has to start with "./" and needs to be relative to the root of the workspace.

**Comment by datajoely** [comment]
Annoyingly I have this working locally - but not on github.dev which I think is a great way to share code tours.
