### ISSUE TITLE
Custom CodeTour Directory not deployed

### ISSUE THREAD

**Issue by NotMyself** [microsoft/codetour#180]
It looks like release 0.0.56 on the marketplace does not contain the custom tour directory feature listed in the release notes. I pulled the package directly from the marketplace and unpacked it. The new setting is not included in the package.json. And no string literal for "customTourDirectory" exists in the distribution.

Is the build process failing?

![Screen Shot 2021-07-07 at 12 35 56 PM](https://user-images.githubusercontent.com/73120/124818450-e5f5bf00-df1f-11eb-9186-f0b706acd01c.png)

**Comment by lostintangent** [comment]
It looks like your change went in _after_ the 0.0.56 release ([diff](https://github.com/microsoft/codetour/compare/v0.0.56...main)), so I just need to ship a new release. I need to fix a regex bug anyways, so let me do that and get a new release out this afternoon. Stay tuned!

**Comment by lostintangent** [comment]
This change has now been shipped. Thanks again for the contribution!
