### ISSUE TITLE
Copying/Pasting files in Explorer via shortcut is not working

### ISSUE THREAD

**Issue by sbartczak-neurosys** [microsoft/codetour#182]
## Description
After installing this extension my shortcuts for copying and pasting in Explorer stopped working. I checked bindings on CTRL+C CTRL+V and saw nothing out of ordinary. Then after disabling this extension it started working again. I suspect it's related to one of those flags that are defined in `filesExplorer.copy` shortcut: `explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !inputFocus`.

## IDE details:
Code - OSS
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-22T15:03:39.218Z
Electron: 11.4.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.32-1-MANJARO

## Extension version
v0.0.58

**Comment by lostintangent** [comment]
I'm unable to repro this issue on macOS/Windows/Ubuntu, and I confirmed that CodeTour isn't doing anything with the copy/paste shortcuts. Is it possible this is related to another extension? Or maybe it's an issue with VS Code + Manjaro? Also, your version of VS Code is pretty old, so it might be worth updating it to the latest?

In the meantime, I'm going to close this as no repo. Please re-open it if you continue to encounter this issue. Thanks!
