### ISSUE TITLE
Can't open URL

### ISSUE THREAD

**Issue by synedra** [microsoft/codetour#189]
In a step, this is simply a no-op:

`[Visit your site](command:vscode.open?["http://localhost:3000"])`

**Comment by lostintangent** [comment]
Could you share what markdown content you're using for the link? Something like this should work: `[Visit your site](https://github.com)`

**Comment by lostintangent** [comment]
You should be able to use a standard Markdown link for HTTP-based URLs, since CodeTour will translate that into the appropriate open behavior. If you use `[Visit your site](http://localhost:3000)`, does that work?

**Comment by lostintangent** [comment]
Closing this as resolved per my previous comment. Let me know if you're hitting an issue here. Thanks!

**Comment by jeluard** [comment]
Note that the following works: `[Open URL](command:simpleBrowser.show?["https://aka.ms/codetour"])`
