### ISSUE TITLE
Auto run tour at startup

### ISSUE THREAD

**Issue by synedra** [microsoft/codetour#190]
Is it possible to make something like this work?

`{
  "auto-run-command.rules": [
      {
          "command": "vsls-contrib.codetour.startTour"
      }
  ]
}`

**Comment by synedra** [comment]
More information, settings.json has this:

{
  "auto-run-command.rules": [
      {
          "command": "vsls-contrib.codetour.startTourByTitle?[\"1. Astra Getting Started\"]"
      }
  ]
}

Error is this:

[Auto Run Command] Condition met but command [vsls-contrib.codetour.startTourByTitle?["1. Astra Getting Started"]] raised an error - [Error: command 'vsls-contrib.codetour.startTourByTitle?["1.' not found]

I've tried the file name, etc.  The tour in question has this:

{
  "$schema": "https://aka.ms/codetour-schema",
  "title": "1. Astra Getting Started",
  "nextTour": "2. Start Building a React app",
  "steps": [
    {
      "title": "Authentication",
      "description": "## Authentication\n\n>> npx create-react-app astra-tik-tok; cd astra-tik-tok\n\n>> astra-setup workshops tiktok\n\n[Visit Astra](https://astra.datastax.com) and follow the instructions in the console to get your token for the astra-setup step.\n\n"
    },
    {
      "title": "Setup Git",
      "description": ">> git init\n\n>> git config --global user.email TikTok@example.com\n\n>> git config --global user.name 'Tik Tok'\n\n>> git add -A\n\n>> git commit -a -m 'Initial commit'\n\n>> git rm -rf yarn.lock src/App.test.js src/reportWebVitals.js src/setupTests.js\n"
    }
  ]
}

So why is it not working?

**Comment by lostintangent** [comment]
I'm not familiar with the auto-run command extension, but the name of the command that you want to execute is simply `codetour.startTour`. So maybe try updating the command name and see if that works?

**Comment by synedra** [comment]
I tried this:
"vsls-contrib.codetour.startTour?[\"1. Astra Getting Started\"]"

And this:
"codetour.startTour?[\"1. Astra Getting Started\"]"

Neither worked.

**Comment by synedra** [comment]
I changed it to startTour with no arguments, but now it's just giving me a dropdown at startup and not picking a particular tour (the primary one).

**Comment by synedra** [comment]
This is mostly working, would just love to know how to describe the tour I want in the call

**Comment by lostintangent** [comment]
The `codeTour.startTourByTitle` command allows you to start a specific tour by title. However, I'm not entirely familiar with how the Auto Run Command extension allows you to specify args. It looks like you provide them as space-seperated values. So you could try `codeTour.startTourByTitle \"<title>\"`

**Comment by synedra** [comment]
[Auto Run Command] Condition met but command [codeTour.startTourByTitle "1. Astra Getting Started"] raised an error - [Error: command 'codeTour.startTourByTitle' not found]

**Comment by lostintangent** [comment]
Apologies, it's `codetour. startTourByTitle`. Note that "codetour" is all lowercase.

**Comment by lostintangent** [comment]
Closing this as resolved
