### ISSUE TITLE
Suggestion:Can I start a 'sub-tour' in my codetour?

### ISSUE THREAD

**Issue by kawhicurry** [microsoft/codetour#219]
A tour with multiple path will be useful.
By doing this,I can record how program is running.Moreover,I can record my decision tree.

**Comment by JonatasAmaral** [comment]
hey

Wouldn't those features combined kind of make a "sub-tour" capability?
* [linking tours, and making one "primary"](https://github.com/microsoft/codetour#tour-references)
* [link to another tour, even on specific point](https://github.com/microsoft/codetour#tour-references)

So your primary tour could at some arbitrary points, have "decision tree" through other `.tour` links.
And if carefully crafted, those could link back


Primary
• 1
• 2
> 
     sub-tour
    •  2.1
    •  2.2
    •  2.3
<
| 3
...

**Comment by kawhicurry** [comment]
Thanks for reply after so long.
These features really solve my problem.
