### ISSUE TITLE
Create new tours in the `customTourDirectory` automatically

### ISSUE THREAD

**Issue by jolo-dev** [microsoft/codetour#220]
Whenever I create a new tour, it creates a file in `.tours`- directory. Even though I have specified a `customTourDirectory`.
There is also a way to put the tours within the `.vscode/tours`- directory but when I create a new tour it does not create it in the given directory.

Is that intention or a bug or am I not doing something wrong?

**Comment by lostintangent** [comment]
This was a bug, which will be fixed in the next extension release this afternoon. Thanks for the feedback!
