### ISSUE TITLE
[feature-request] File-reference in markdown - line numbers?

### ISSUE THREAD

**Issue by Gvald** [microsoft/codetour#222]
I think that adding the ability to link not just files, but also reference to specific line in file in a step can be really useful.
Just like in [here](https://github.com/microsoft/codetour/blob/3f9153d75c816c346b805ef9e75a36cdf4553a64/src/player/index.ts#L72)
I already tried with `[file](path/to/file:XX)`, but got an error from VSCode that file is not exist.
IMO - this shouldn't be too hard to implement, if vscode already supports this feature, of course.

I have no problem working on this PR, just need some references.
I know already [this link](https://github.com/microsoft/codetour/blob/3f9153d75c816c346b805ef9e75a36cdf4553a64/src/player/index.ts#L72) is related, Will be happy to basic guidance.

**Comment by lostintangent** [comment]
This is now fixed, and will be included in the next marketplace release. Thanks for the feedback!
