### ISSUE TITLE
Is possible to load custom icons/pictures?

### ISSUE THREAD

**Issue by R3uan3** [microsoft/codetour#236]
How do i load custom icons/pictures into the titles of the steps?

I tried:
```
  "$schema": "https://aka.ms/codetour-schema",
  "title": "🏃 Getting Started",
  "steps": [
    {
      "description": "### ![Image](./debug.png) 📌"
    },
```
It's not loading the picture, it shows `[Image](./debug.png)` as the title.

When I hover it shows the picture correctly:
![image](https://user-images.githubusercontent.com/103058225/161819319-516c4cb0-c7a2-4bee-a2ad-2ed498822c17.png)

Also, is possible to set a different icon for each step? (I mean these icons inside the green rect)

**Comment by R3uan3** [comment]
> What scenario/use case did you have in mind?

To make it easy to find a step when you have too many steps, just looking at the icon would be easier/faster to recognize a step than reading her title.

**Comment by lostintangent** [comment]
Got it, thanks for that detail. I haven't heard this feedback from other users, so I probably won't be able to prioritize this for a bit. But if you wanted to submit a PR, that would be awesome. Otherwise, I can try to get to this is a couple of weeks.

**Comment by R3uan3** [comment]
@lostintangent hello did you got any free time for it?

**Comment by R3uan3** [comment]
@lostintangent hi

**Comment by R3uan3** [comment]
@lostintangent hello

**Comment by R3uan3** [comment]
@lostintangent hello how many weeks you were talking about
