### ISSUE TITLE
Allow defining alternate paths within a tour

### ISSUE THREAD

**Issue by johnpapa** [microsoft/codetour#27]
Wicked cool feature ideas ... imagine being able to ask the user where they want to go next?

We could provide paths on the tour to do this. Tour contains paths, paths contain steps

So there would be a hierarchy of these. For example ...

I wan to start by showing the `index.html`, then steps in the `main.js`, then the `App.svelte` component (in a svelte app). At this point I can ask the user if they want to go to the path for building and running the app in the `package.json` or the path to see the code in the main components.

Paths:

-  paths could be rearranged
-  could be in a given sequence or out of sequence (dont show build path unless the user asks for that)
-  steps can be text OR they are a prompt asking which of a set of paths the user wants to go to next

A simpler version of this would be to simply allow grouping of steps into a path, so a set of steps can be visually broken out and rearranged.

**Comment by lostintangent** [comment]
@johnpapa Currently, you could create multiple tours and let the user decide which one they want based on title/description. That said, I agree that enabling a "choose your own adventure" experience could be cool as well. I think there's a bunch of work left to do in order to solidify the current "guided path" experience, so I might explore this enhancement later.

**Comment by lostintangent** [comment]
Now that CodeTour supports linking tours, and adding links to other tours, I'm going to close this as resolved. In this case, the “tour path” can be defined by breaking up a tour into numerous other tours, and then linking them together.

Beyond that, I think we’ll want to allow better organization of tours, and so we can track that enhancement via #50. Let me know if this doesn't accurately reflect your thoughts here, and we can reopen the issue. Thanks!
