### ISSUE TITLE
How to link exported tour file or gist link to local workspace？

### ISSUE THREAD

**Issue by ZhongHaoAustin** [microsoft/codetour#294]
Thank you for the excellent work!

Upon completing a tour and exporting it as a file or uploading it to a gist, I've noticed that when I open the tour from the file or gist link, I only find the tour in the snippet file instead of the entire project. This makes it challenging for us to seamlessly continue the tour steps if we wish to explore further within the project, especially when the file is not in the CodeTour snippet files.

I look forward to your response!

**Comment by stunited-thien** [comment]
@ZhongHaoAustin  I dont know if this is an bug or not but when I opened the exported tour file via the icon folder in codetour explorer, it didn't open the file project for that tour. I then opened that tour file via command palette and the file project did open. I hope this may help you
