### ISSUE TITLE
Problem related to multi-root workspace

### ISSUE THREAD

**Issue by mlsoar** [microsoft/codetour#87]
It's a great extenstion helping me review code. I met a problem these days and please help.

When using CodeTour in my multi-root workspace, I choosed the first folder (e.g., `path_a`) to save my tour file (`path_a/.tours/foo.tour`).

I can record the step for file `A.md` in the second folder (e.g., `path_b`) of my workspace, which is confirmed according to the content of .tour file. But when playback the tour, steps which are not in the first folder didnot show.

I checked the path to file of the problem step and found it to be right. And I read the #1 and #13 but could not find some way to address the problem.

Any help will be appreciated, thanks :smiley:

**Comment by gsmile** [comment]
Hi @mapleleaf-soar, thanks for flagging. To clarify, are you saying that the tour is missing steps when there is more than one root folder? cc @lostintangent

**Comment by mapleleaf-soar** [comment]
Sorry for my unclear expression. Some steps are not "missing". The comment contents of these steps are indeed in the `.tours/foo.tour`. I just can not see them after "starting tour".

My workspace is:

> path_a
> ├── a.md
> ├── .tours
> │   └── foo.tour
> path_b
> └── b.md

When I click step 1 and 2,
![image](https://user-images.githubusercontent.com/13448119/91650530-6bfcda00-eab3-11ea-8bf3-03e79067b0c5.png)
![image](https://user-images.githubusercontent.com/13448119/91650542-86cf4e80-eab3-11ea-95d4-641408c5a4f6.png)

Thanks.

**Comment by gsmile** [comment]
Thanks for this! We will look into this issue and see if we can get it fixed.

**Comment by lostintangent** [comment]
This is fixed in `v0.0.49` 👍🏻

**Comment by mlsoar** [comment]
I tested the `v0.0.49` and it worked! Thanks!

**Comment by lostintangent** [comment]
Awesome! Thanks for confirming 🤗
