### ISSUE TITLE
xAPI support for completing steps or tours

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#99]
We're beginning to see interest in CodeTour to be used as a complement for learning/training materials. In cases where the underlying learning platform had an LRS/xAPI service that it used to track user activity, then it would be valuable if the completion/progress of CodeTour steps were reported to it. In particular, we could introduce the ability to send xAPI "statements" to a configure xAPI service whenever a step or tour was completed.

**Comment by lostintangent** [comment]
This request makes a ton of sense and I'd love to add it! The primary question we'll need to think about is how we would track user identity. After looking into xAPI support, I think it will be really simple for us to introduce this support to CodeTour. However, we'll need to know the URL of the xAPI server and the credentials for the end-user. I could imagine the xAPI URL being a property in the `*.tour` file, but in the case of user authentication, that would likely need to be addressed by something else (e.g. a VS Code extension), and then exposed to CodeTour in a way that we could provide SSO for the user.

**Comment by gsmile** [comment]
We also received feedback from one of our internal customers that sending data back to the server for tracking completion of courses would be helpful for them, though they did not specifically mention using xAPI. I don't believe they have infrastructure set up to receive data yet.

**Comment by lostintangent** [comment]
Closing this for now, until we hear more feedback on this. Right now, it's unclear how we'd implement support for this without having some sort of user-authentication experience, which would be not trivial to do.
